// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: author.sql

package postgres

import (
	"context"
)

const getAuthorById = `-- name: GetAuthorById :one
SELECT
  id, name, created_at, updated_at
FROM
  author
WHERE
  id = $1
`

func (q *Queries) GetAuthorById(ctx context.Context, id int32) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorById, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
