// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID        int32
	Title     string
	Content   string
	AuthorID  pgtype.Int4
	UpdatedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type ArticleCategory struct {
	ID         int32
	ArticleID  int32
	CategoryID int32
}

type Author struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Category struct {
	ID        int32
	Name      string
	Tag       string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
