// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateArticle(ctx context.Context, arg CreateArticleParams) error
	CreateArticles(ctx context.Context, arg []CreateArticlesParams) *CreateArticlesBatchResults
	DeleteArticle(ctx context.Context, id int32) error
	GetArticleByID(ctx context.Context, id int32) (Article, error)
	GetArticleByTitle(ctx context.Context, title string) (Article, error)
	GetAuthorByID(ctx context.Context, id int32) (Author, error)
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error)
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) error
}

var _ Querier = (*Queries)(nil)
