name: Go Test

on:
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Set .env
        run: cp .env.sample .env

      - name: Linter
        run: make lint

      - name: Test
        run: make tests
